import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { OrganizedEscrowData, ParsedMilestone } from "@/mappers/escrow-mapper";
import { NetworkType } from "@/lib/network-config";

interface jsPDFWithPlugin extends jsPDF {
    lastAutoTable?: {
        finalY: number;
    };
}

/**
 * Generates a professional PDF report for an escrow.
 */
export const exportEscrowToPDF = (
    organized: OrganizedEscrowData,
    network: NetworkType
) => {
    const doc = new jsPDF() as jsPDFWithPlugin;
    const timestamp = new Date().toLocaleString();
    const pageWidth = doc.internal.pageSize.getWidth();

    // --- 1. Report Header ---
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("Escrow Report", 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by Trustless Work Escrow Viewer`, 14, 30);
    doc.text(`Network: ${network.charAt(0).toUpperCase() + network.slice(1)}`, 14, 35);
    doc.text(`Export Timestamp: ${timestamp}`, 14, 40);

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 45, pageWidth - 14, 45);

    // --- 2. Escrow Summary ---
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Escrow Summary", 14, 55);

    const summaryData = [
        ["Escrow ID", organized.properties.escrow_id],
        ["Description", organized.description],
        ["Escrow Type", organized.escrowType === "multi-release" ? "Multi-Release" : "Single-Release"],
        ["Engagement ID", organized.properties.engagement_id || "N/A"],
        ["Total Escrowed Amount", organized.properties.amount],
        ["Current Balance", organized.properties.balance],
        ["Platform Fee", organized.properties.platform_fee],
        ["Trustless Work Fee", "0.3%"],
    ];

    autoTable(doc, {
        startY: 60,
        body: summaryData,
        theme: "plain",
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 50 } },
    });

    // --- 3. Escrow Status ---
    const lastAutoTable1 = doc.lastAutoTable;
    const statusY = (lastAutoTable1 ? lastAutoTable1.finalY : 100) + 10;
    doc.setFontSize(16);
    doc.text("Escrow Status", 14, statusY);

    const statusData = [
        ["Progress", `${organized.progress}%`],
        ["Lifecycle State", organized.flags.lifecycle_state],
        ["Dispute State", organized.flags.dispute_flag],
        ["Release State", organized.flags.release_flag],
        ["Resolution State", organized.flags.resolved_flag],
    ];

    autoTable(doc, {
        startY: statusY + 5,
        body: statusData,
        theme: "plain",
        styles: { fontSize: 10, cellPadding: 2 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 50 } },
    });

    // --- 4. Assigned Roles ---
    const lastAutoTable2 = doc.lastAutoTable;
    const rolesY = (lastAutoTable2 ? lastAutoTable2.finalY : 150) + 10;
    doc.setFontSize(16);
    doc.text("Assigned Roles", 14, rolesY);

    const rolesData = Object.entries(organized.roles).map(([role, address]) => [
        role.charAt(0).toUpperCase() + role.slice(1),
        address,
    ]);

    autoTable(doc, {
        startY: rolesY + 5,
        head: [["Role Name", "Wallet Address"]],
        body: rolesData,
        theme: "striped",
        headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: "bold" },
        styles: { fontSize: 9 },
    });

    // --- 5. Milestones ---
    if (organized.milestones && organized.milestones.length > 0) {
        const lastAutoTable3 = doc.lastAutoTable;
        const milestonesY = (lastAutoTable3 ? lastAutoTable3.finalY : 200) + 10;

        let milestonesStartY = milestonesY + 15;

        // Check if we need a new page for milestones
        if (milestonesY > 240) {
            doc.addPage();
            doc.setFontSize(16);
            doc.text("Milestones", 14, 22);
            milestonesStartY = 30; // Reset startY for new page
        } else {
            doc.setFontSize(16);
            doc.text("Milestones", 14, milestonesY);
            milestonesStartY = milestonesY + 5;
        }

        const milestoneHead = organized.escrowType === "multi-release"
            ? [["ID", "Title", "Description", "Amount", "Status", "Approved"]]
            : [["ID", "Title", "Description", "Status", "Approved"]];

        const milestoneBody = organized.milestones.map((m: ParsedMilestone) => {
            const base = [
                String(m.id + 1),
                m.title,
                m.description || "",
                m.status,
                m.approved ? "Yes" : "No",
            ];
            if (organized.escrowType === "multi-release") {
                base.splice(3, 0, m.amount || "0.00");
            }
            return base;
        });

        autoTable(doc, {
            startY: milestonesStartY,
            head: milestoneHead,
            body: milestoneBody,
            theme: "striped",
            headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: "bold" },
            styles: { fontSize: 9 },
        });
    }

    // --- 6. Footer ---
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            "Generated by Trustless Work Escrow Viewer - https://trustlesswork.com",
            14,
            doc.internal.pageSize.getHeight() - 10
        );
        doc.text(
            `Page ${i} of ${pageCount}`,
            doc.internal.pageSize.getWidth() - 30,
            doc.internal.pageSize.getHeight() - 10
        );
    }

    // Download PDF
    const filename = `EscrowReport_${organized.properties.escrow_id.substring(0, 8)}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};
